### ISSUE TITLE
AppLovinQualityService breaks Xcode 16 beta compilation

### ISSUE THREAD

**Issue by hberenger** [AppLovin/AppLovin-MAX-Ad-Review-SDK-iOS#1]
Hi AppLovin team,

Everything is in the issue title: Ad Review seems to break compilation of iOS apps with Xcode 16 beta. We noticed this issue while preparing for the imminent release of Xcode 16.

### Environment
* `AppLovinSDK` 12.5.0 and 12.6.1
* AppLovin Quality Service 7.4.2
* Xcode 16 beta 6
* MacOS Sonoma 14.5 on Apple M1 Pro

### Issue details
To be more precise:
* I have an iOS native app which integrates `AppLovinSDK` 12.5.0 along with `AdReview` (`AppLovinQualityServicePlugin`)
* `AppLovinSDK` in integrated via SPM, and `AdReview` using the ruby configuration file downloaded from AppLovin website, as per the integration guide
* The app compiles well using Xcode 15.4 (and is published on the AppStore)
* When trying to build the same app using Xcode 16.0 beta 6, the build fails during the `AppLovinQualityService` build phase (which has been added to the project by the AdReview configuration script)
* Build is broken for both iOS simulator and arm64 (iOS device) architectures.

Here is the output of the build phase when the app is built with Xcode 15.4:

```
AppLovin Quality Service Plugin for Xcode
Copyright © 2024 AppLovin. All rights reserved.
Plugin Version: 7.4.2 (7040200)
INFO: Plugin Version: 7.4.2 (7040200)
INFO: Configuration read from AppLovinQualityServiceSetup-ios.rb

Uploading data to AppLovin Server (api2.safedk.com)...
```

On the contrary, this is the error output of the build phase when building with Xcode 16 beta:

```
AppLovin Quality Service Plugin for Xcode
Copyright © 2024 AppLovin. All rights reserved.
Plugin Version: 7.4.2 (7040200)
INFO: Plugin Version: 7.4.2 (7040200)
INFO: Configuration read from AppLovinQualityServiceSetup-ios.rb

INFO: No classes found in path: [APP DERIVED DATA PATH]/Build/Products/Debug-iphonesimulator/MyApp.app/MyApp
ERROR: The AppLovinQualityService Pod was not identified in your app. Please clean and rebuild your project.
If the problem persists - please reinstall the AppLovinQualityService Pod.
```

(I replaced the actual Derived Data path by `[APP DERIVED DATA PATH]` in the above, along with the true app name)

Cleaning everything / deleting derived datas does not fix the problem, neither does reinstalling `AppLovinQualityService`.

### Steps to reproduce

You can find in attachment a sample Xcode project with which you can easily reproduce the problem:
* it builds with Xcode 15.4
* it produces the above compilation error with Xcode 16 beta

[AppLovinQualityServiceBuildIssue.zip](https://github.com/user-attachments/files/16909060/AppLovinQualityServiceBuildIssue.zip)

Do you have an idea about what's happening? Will this be fixed on your side by a new version of AppLovinQualityService ?

Thanks a lot!

**Comment by alvarshahanji** [comment]
I could integrate Ad Review and build the app successfully on Xcode 16 beta 6. Could you try reproducing the issue using our [demo app](https://github.com/AppLovin/AppLovin-MAX-SDK-iOS) following the instructions in our [doc](https://developers.applovin.com/en/max/ios/overview/integration)?

**Comment by alvarshahanji** [comment]
@hberenger Just tested with the sample project you attached and noticed it is using Swift. I could reproduce the issue with our [swift demo app](https://github.com/AppLovin/AppLovin-MAX-SDK-iOS/tree/master/AppLovin%20MAX%20Demo%20App%20-%20Swift) as well. We will look into it and let you know. Thank you.

cc: @orilentz

**Comment by hberenger** [comment]
Thanks a lot @alvarshahanji!

**Comment by alvarshahanji** [comment]
Fix is released with Ad Review [7.4.3](https://github.com/AppLovin/AppLovin-MAX-Ad-Review-SDK-iOS/releases/tag/7.4.3). Please update. Thank you.

**Comment by hberenger** [comment]
Hello @alvarshahanji,
I can confirm that compilation is fixed by the latest AdReview version. This issue can be closed.
Thanks for the prompt action!
